---
- name: Kubeadm init
  shell: kubeadm init --image-repository {{ k8s_image_repo }} --pod-network-cidr={{ pod_network_cidr }} --service-cidr={{ service_cidr }} creates=/etc/kubernetes/admin.conf
  when: node_role == 'master'
  register: init_out

- name: Display init output
  debug:
    var: init_out.stdout
  when: init_out.stdout is defined

- name: Create directory .kube
  file:
    path: ~/.kube
    state: directory

- name: Copy admin.conf
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config

- name: Deploy pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Get join command
  shell: kubeadm token create --print-join-command
  when: node_role == 'master'
  register: cluster_join_command

- name: Distribute join command
  set_fact:
    join_cmd: "{{ cluster_join_command.stdout }}"
  when: cluster_join_command.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

