---
- name: Enable time synchronization
  systemd:
    name: chrony.service
    state: started
    enabled: yes

- name: Disable swap partition
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present

- name: Disable swap partition from auto-mounting
  shell: "sed -ri '/^[^#]*swap/s@^@#@' /etc/fstab"

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Automatically load kernel modules
  shell: echo br_netfilter > /etc/modules-load.d/k8s.conf

- name: Allow iptables to inspect bridged traffic
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
