---
- include_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'

- name: Change cgroupdriver to systemd
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker

- name: Restart docker to change cgroupdriver for k8s right now
  meta: flush_handlers
