---
- include_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'

- name: Change cgroupdriver to systemd
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker
